# Generated by Django 5.2.9 on 2026-03-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("retrieval", "Retrieval Parameters"),
                            ("chunking", "Chunking Parameters"),
                            ("model", "Model Selection"),
                            ("advanced", "Advanced Options"),
                        ],
                        default="retrieval",
                        help_text="Configuration category",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(help_text="Configuration values")),
                (
                    "previous_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Previous configuration values",
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        default="system",
                        help_text="Who made the change",
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for the configuration change",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the active configuration",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the change was made"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(help_text="The user's query text")),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("concept", "Concept/Definition"),
                            ("method", "Method/Process"),
                            ("comparison", "Comparison"),
                            ("reason", "Reason/Explanation"),
                            ("example", "Example/Application"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of query",
                        max_length=20,
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(help_text="Query latency in milliseconds"),
                ),
                (
                    "cache_hit",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the result was served from cache",
                    ),
                ),
                (
                    "results_count",
                    models.IntegerField(
                        default=0, help_text="Number of results returned"
                    ),
                ),
                (
                    "top_k",
                    models.IntegerField(
                        default=3, help_text="Top-K parameter used for retrieval"
                    ),
                ),
                (
                    "similarity_threshold",
                    models.FloatField(
                        default=0.6, help_text="Similarity threshold used"
                    ),
                ),
                (
                    "retrieved_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of retrieved document references",
                    ),
                ),
                (
                    "user_feedback",
                    models.BooleanField(
                        blank=True,
                        help_text="User feedback: True=helpful, False=not helpful",
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Session identifier",
                        max_length=100,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="LLM model used for generation",
                        max_length=100,
                    ),
                ),
                (
                    "answer_length",
                    models.IntegerField(
                        default=0, help_text="Length of generated answer in characters"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the query was made"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("avg_latency", "Average Latency"),
                            ("p95_latency", "P95 Latency"),
                            ("query_count", "Query Count"),
                            ("cache_hit_rate", "Cache Hit Rate"),
                            ("embedding_time", "Embedding Time"),
                            ("retrieval_time", "Retrieval Time"),
                            ("index_size", "Index Size"),
                            ("chunk_count", "Chunk Count"),
                            ("document_count", "Document Count"),
                            ("memory_usage", "Memory Usage"),
                            ("disk_usage", "Disk Usage"),
                            ("similarity_score", "Similarity Score"),
                        ],
                        help_text="Metric name",
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField(help_text="Metric value")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metric metadata"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the metric was recorded"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RenameIndex(
            model_name="suggestedquestion",
            new_name="django_app__created_606594_idx",
            old_name="django_app__created_ea3d9f_idx",
        ),
        migrations.RenameIndex(
            model_name="suggestedquestion",
            new_name="django_app__questio_dc5e27_idx",
            old_name="django_app__questio_2c8f5e_idx",
        ),
        migrations.RenameIndex(
            model_name="suggestedquestion",
            new_name="django_app__click_c_36f592_idx",
            old_name="django_app__click__c3a3c3_idx",
        ),
        migrations.AddIndex(
            model_name="confighistory",
            index=models.Index(
                fields=["category", "-created_at"],
                name="django_app__categor_9686fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="confighistory",
            index=models.Index(
                fields=["-created_at"], name="django_app__created_a02339_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="confighistory",
            index=models.Index(
                fields=["is_active"], name="django_app__is_acti_d624b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querylog",
            index=models.Index(
                fields=["-created_at"], name="django_app__created_e5d796_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querylog",
            index=models.Index(
                fields=["query_type"], name="django_app__query_t_830ee5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querylog",
            index=models.Index(
                fields=["cache_hit"], name="django_app__cache_h_e3acc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querylog",
            index=models.Index(
                fields=["latency_ms"], name="django_app__latency_ca00f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemmetric",
            index=models.Index(
                fields=["name", "-timestamp"], name="django_app__name_00d85a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemmetric",
            index=models.Index(
                fields=["-timestamp"], name="django_app__timesta_557c81_idx"
            ),
        ),
    ]
