# Generated by Django 5.2.9 on 2026-03-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0002_confighistory_querylog_systemmetric_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="call_type",
            field=models.CharField(
                default="qa", help_text="Type of LLM call", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="querylog",
            name="error_message",
            field=models.TextField(
                blank=True, default="", help_text="Error message if call failed"
            ),
        ),
        migrations.AddField(
            model_name="querylog",
            name="llm_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LLM provider: gemini / openrouter / local_llm",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="querylog",
            name="llm_status",
            field=models.CharField(
                default="success",
                help_text="Call status: success / error",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="querylog",
            index=models.Index(
                fields=["llm_provider"], name="django_app__llm_pro_495772_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querylog",
            index=models.Index(
                fields=["llm_status"], name="django_app__llm_sta_d350a3_idx"
            ),
        ),
    ]
