# Generated by Django 5.2.9 on 2026-08-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_app",
            "0004_alter_querylog_call_type_alter_querylog_llm_provider_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="querylog",
            name="call_type",
            field=models.CharField(
                choices=[
                    ("qa", "Question Answering"),
                    ("summary", "Summarization"),
                    ("suggestion", "Question Suggestion"),
                    ("citation", "Citation"),
                    ("rewrite", "Conversation Rewrite"),
                ],
                default="qa",
                help_text="Type of LLM call",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MCQQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        default=list,
                        help_text="List of MCQ question dicts (id, question, options, correct_answer, explanation, difficulty, source_doc)",
                    ),
                ),
                (
                    "document_names",
                    models.TextField(
                        help_text="Comma-separated list of document names this quiz was generated from"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("mixed", "Mixed"),
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="mixed",
                        help_text="Requested difficulty level",
                        max_length=10,
                    ),
                ),
                ("question_count", models.IntegerField(default=0)),
                (
                    "llm_provider",
                    models.CharField(
                        default="local_llm",
                        help_text="LLM provider used for generation",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this quiz was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this quiz was last updated"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="django_app__created_e6ded8_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MCQAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=list, help_text="List of {question_id, selected} dicts"
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this attempt was submitted"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="The quiz this attempt belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="django_app.mcqquiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="django_app__created_ad3632_idx"
                    )
                ],
            },
        ),
    ]
