# Generated by Django 5.2.9 on 2026-08-13 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0005_alter_querylog_call_type_mcqquiz_mcqattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_id",
                    models.CharField(help_text="Indexed document name", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("interrupted", "Interrupted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=40)),
                ("progress", models.IntegerField(default=0, help_text="Percent 0-100")),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "detected_language",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("topics", models.JSONField(blank=True, default=list)),
                ("result_markdown", models.TextField(blank=True, default="")),
                ("result_json", models.JSONField(blank=True, default=dict)),
                ("citations", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, default="", max_length=40)),
                ("error_message", models.TextField(blank=True, default="")),
                ("cancel_requested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="django_app__created_8e2fb5_idx"
                    ),
                    models.Index(
                        fields=["status"], name="django_app__status_553564_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SummaryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("stage", "Stage"),
                            ("progress", "Progress"),
                            ("partial", "Partial"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="django_app.summaryjob",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
