# Generated by Django 5.2.9 on 2026-08-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0005_alter_querylog_call_type_mcqquiz_mcqattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querylog",
            name="call_type",
            field=models.CharField(
                choices=[
                    ("qa", "Question Answering"),
                    ("summary", "Summarization"),
                    ("suggestion", "Question Suggestion"),
                    ("citation", "Citation"),
                    ("rewrite", "Conversation Rewrite"),
                    ("mcq", "MCQ Generation"),
                ],
                default="qa",
                help_text="Type of LLM call",
                max_length=20,
            ),
        ),
    ]
