# Generated by Django 5.2.9 on 2026-08-13 08:39

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List  # noqa: F401

from django.db import migrations
from django.utils import timezone

logger = logging.getLogger(__name__)

SUMMARY_HISTORY_FILE = (
    Path(__file__).resolve().parents[2] / "data" / "summary_history.json"
)


def _parse_timestamp(value: Any):
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except (ValueError, TypeError):
        return timezone.now()


def migrate_summary_history(apps, schema_editor):
    SummaryJob = apps.get_model("django_app", "SummaryJob")

    if not SUMMARY_HISTORY_FILE.exists():
        return

    try:
        with SUMMARY_HISTORY_FILE.open("r", encoding="utf-8") as history_file:
            data = json.load(history_file)
    except (OSError, json.JSONDecodeError):
        logger.warning("Could not read legacy summary history, skipping")
        return

    if not isinstance(data, list):
        return

    for entry in data:
        if not isinstance(entry, dict):
            continue
        documents = entry.get("documents")
        if not isinstance(documents, list) or not documents:
            logger.warning(
                "Skipping malformed legacy summary entry %r", entry.get("id")
            )
            continue

        legacy_config = entry.get("config") or {}

        try:
            legacy_config = dict(legacy_config)
            legacy_config["legacy_documents"] = [str(doc) for doc in documents]
            SummaryJob.objects.create(
                document_id=str(documents[0]),
                status="completed",
                stage="done",
                progress=100,
                config=legacy_config,
                detected_language="",
                topics=[],
                result_markdown=str(entry.get("summary") or ""),
                result_json={
                    "legacy": True,
                    "documents": [str(doc) for doc in documents],
                    "comparison": entry.get("comparison") or [],
                },
                citations=list(entry.get("citations") or []),
                error_code="",
                error_message="",
                completed_at=_parse_timestamp(entry.get("timestamp")),
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "Failed to migrate legacy summary %s: %s", entry.get("id"), exc
            )


def reverse_migrate(apps, schema_editor):
    SummaryJob = apps.get_model("django_app", "SummaryJob")
    SummaryJob.objects.filter(result_json__legacy=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0006_summary_jobs"),
    ]

    operations = [
        migrations.RunPython(migrate_summary_history, reverse_migrate),
    ]
