# Generated by Django 5.2.9 on 2026-08-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0006_alter_querylog_call_type"),
        ("django_app", "0007_migrate_legacy_summary_history"),
    ]

    operations = []
