# Generated by Django 5.2.9 on 2026-08-13

from django.db import migrations, models


def remap_mcq_query_logs(apps, schema_editor):
    """Re-label legacy MCQ generation LLM logs as quiz calls."""
    QueryLog = apps.get_model("django_app", "QueryLog")
    QueryLog.objects.filter(call_type="mcq").update(call_type="quiz")


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0008_merge_20260813_1824"),
    ]

    operations = [
        migrations.RunPython(remap_mcq_query_logs, migrations.RunPython.noop),
        migrations.DeleteModel(name="MCQAttempt"),
        migrations.DeleteModel(name="MCQQuiz"),
        migrations.AlterField(
            model_name="querylog",
            name="call_type",
            field=models.CharField(
                choices=[
                    ("qa", "Question Answering"),
                    ("summary", "Summarization"),
                    ("suggestion", "Question Suggestion"),
                    ("citation", "Citation"),
                    ("rewrite", "Conversation Rewrite"),
                ],
                default="qa",
                help_text="Type of LLM call",
                max_length=20,
            ),
        ),
    ]
