from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static

from django_app import views

urlpatterns = [
    # API endpoints
    path("api", views.root),
    path("api/", views.root),
    path("api/upload", views.upload_pdf),
    path("api/upload/", views.upload_pdf),
    path("api/upload/status", views.upload_index_status),
    path("api/upload/status/", views.upload_index_status),
    path("api/files", views.list_files),
    path("api/files/", views.list_files),
    path("api/documents", views.list_documents),
    path("api/documents/", views.list_documents),
    path("api/documents/delete", views.delete_document),
    path("api/documents/delete/", views.delete_document),
    path("api/summarize", views.summarize_doc),
    path("api/summarize/", views.summarize_doc),
    path("api/podcast", views.generate_podcast),
    path("api/podcast/", views.generate_podcast),
    path("api/ask", views.ask_question),
    path("api/ask/", views.ask_question),
    path("api/chat", views.ask_qwen),
    path("api/chat/", views.ask_qwen),
    path("api/ask_qwen", views.ask_qwen),
    path("api/ask_qwen/", views.ask_qwen),
    path("api/chat/citations", views.ask_with_citations),
    path("api/chat/citations/", views.ask_with_citations),
    path("api/settings", views.settings_handler),
    path("api/settings/", views.settings_handler),
    path("api/rag-config", views.get_rag_config),
    path("api/rag-config/", views.get_rag_config),
    path("api/rag-config/update", views.update_rag_config),
    path("api/rag-config/update/", views.update_rag_config),
    path("api/index/reset", views.reset_faiss_index),
    path("api/index/reset/", views.reset_faiss_index),
    path("chat-htmx", views.chat_htmx),
    path("chat-htmx/", views.chat_htmx),
    path("api/retrieve", views.retrieve_chunks),
    path("api/retrieve/", views.retrieve_chunks),
    path("api/compare", views.compare_documents),
    path("api/compare/", views.compare_documents),
    # Dashboard API endpoints
    path("api/dashboard/stats", views.dashboard_stats),
    path("api/dashboard/stats/", views.dashboard_stats),
    path("api/dashboard/metrics", views.dashboard_metrics),
    path("api/dashboard/metrics/", views.dashboard_metrics),
    path("api/dashboard/chunks/distribution", views.dashboard_chunks_distribution),
    path("api/dashboard/chunks/distribution/", views.dashboard_chunks_distribution),
    path(
        "api/dashboard/similarity/distribution", views.dashboard_similarity_distribution
    ),
    path(
        "api/dashboard/similarity/distribution/",
        views.dashboard_similarity_distribution,
    ),
    path("api/dashboard/documents/timeline", views.dashboard_documents_timeline),
    path("api/dashboard/documents/timeline/", views.dashboard_documents_timeline),
    path("api/dashboard/config", views.dashboard_update_config),
    path("api/dashboard/config/", views.dashboard_update_config),
    path("api/dashboard/reindex", views.dashboard_reindex),
    path("api/dashboard/reindex/", views.dashboard_reindex),
    # Admin Dashboard API endpoints (Phase 1)
    path("api/admin/stats", views.admin_stats),
    path("api/admin/stats/", views.admin_stats),
    path("api/admin/query-stats", views.admin_query_stats),
    path("api/admin/query-stats/", views.admin_query_stats),
    path("api/admin/debug/retrieval", views.admin_debug_retrieval),
    path("api/admin/debug/retrieval/", views.admin_debug_retrieval),
    path("api/admin/documents", views.admin_documents),
    path("api/admin/documents/", views.admin_documents),
    path("api/admin/documents/<str:doc_id>/chunks", views.admin_document_chunks),
    path("api/admin/documents/<str:doc_id>/chunks/", views.admin_document_chunks),
    path("api/admin/documents/<str:doc_id>/delete", views.admin_delete_document),
    path("api/admin/documents/<str:doc_id>/delete/", views.admin_delete_document),
    path("api/admin/documents/<str:doc_id>/reindex", views.admin_reindex_document),
    path("api/admin/documents/<str:doc_id>/reindex/", views.admin_reindex_document),
    path("api/admin/indexing-status", views.admin_indexing_status),
    path("api/admin/indexing-status/", views.admin_indexing_status),
    # Admin Analytics (Phase 2)
    path("api/admin/analytics/document/<str:doc_id>", views.admin_document_analytics),
    path("api/admin/analytics/document/<str:doc_id>/", views.admin_document_analytics),
    path("api/admin/analytics/query-clusters", views.admin_query_clusters),
    path("api/admin/analytics/query-clusters/", views.admin_query_clusters),
    path("api/admin/analytics/failures", views.admin_failure_analysis),
    path("api/admin/analytics/failures/", views.admin_failure_analysis),
    path("api/admin/visualization/embeddings", views.admin_embedding_visualization),
    path("api/admin/visualization/embeddings/", views.admin_embedding_visualization),
    path("api/admin/analytics/chunk-quality", views.admin_chunk_quality),
    path("api/admin/analytics/chunk-quality/", views.admin_chunk_quality),
    path("api/admin/debug/trace", views.admin_retrieval_trace),
    path("api/admin/debug/trace/", views.admin_retrieval_trace),
    # A/B Testing
    path("api/admin/abtests", views.admin_ab_tests),
    path("api/admin/abtests/", views.admin_ab_tests),
    path("api/admin/abtest/create", views.admin_ab_test_create),
    path("api/admin/abtest/create/", views.admin_ab_test_create),
    path("api/admin/abtest/<int:test_id>/start", views.admin_ab_test_start),
    path("api/admin/abtest/<int:test_id>/start/", views.admin_ab_test_start),
    path("api/admin/abtest/<int:test_id>/stop", views.admin_ab_test_stop),
    path("api/admin/abtest/<int:test_id>/stop/", views.admin_ab_test_stop),
    path("api/admin/abtest/record", views.admin_ab_test_record),
    path("api/admin/abtest/record/", views.admin_ab_test_record),
    path("api/admin/abtest/<int:test_id>/results", views.admin_ab_test_results),
    path("api/admin/abtest/<int:test_id>/results/", views.admin_ab_test_results),
    # Phase 3: Smart Operations
    path("api/admin/alerts/current", views.admin_alerts_current),
    path("api/admin/alerts/current/", views.admin_alerts_current),
    path("api/admin/alerts/acknowledge", views.admin_alerts_acknowledge),
    path("api/admin/alerts/acknowledge/", views.admin_alerts_acknowledge),
    path("api/admin/capacity/forecast", views.admin_capacity_forecast),
    path("api/admin/capacity/forecast/", views.admin_capacity_forecast),
    path("api/admin/selfhealing/events", views.admin_selfhealing_events),
    path("api/admin/selfhealing/events/", views.admin_selfhealing_events),
    path("api/admin/selfhealing/config", views.admin_selfhealing_config),
    path("api/admin/selfhealing/config/", views.admin_selfhealing_config),
    path("api/admin/cost/analysis", views.admin_cost_analysis),
    path("api/admin/cost/analysis/", views.admin_cost_analysis),
    path("api/admin/analytics/users", views.admin_user_behavior),
    path("api/admin/analytics/users/", views.admin_user_behavior),
    path("api/admin/reports/generate", views.admin_generate_report),
    path("api/admin/reports/generate/", views.admin_generate_report),
    path("api/admin/reports/history", views.admin_reports_history),
    path("api/admin/reports/history/", views.admin_reports_history),
    path("api/admin/health/score", views.admin_health_score),
    path("api/admin/health/score/", views.admin_health_score),
    # Embedding Model Management endpoints
    path("api/settings/embedding-models", views.list_embedding_models),
    path("api/settings/embedding-models/", views.list_embedding_models),
    path("api/settings/embedding-model", views.get_current_embedding_model),
    path("api/settings/embedding-model/", views.get_current_embedding_model),
    path("api/settings/embedding-model/switch", views.switch_embedding_model),
    path("api/settings/embedding-model/switch/", views.switch_embedding_model),
    path("api/settings/embedding-model/test", views.test_embedding_model),
    path("api/settings/embedding-model/test/", views.test_embedding_model),
    path("api/settings/embedding-model/metrics", views.get_embedding_model_metrics),
    path("api/settings/embedding-model/metrics/", views.get_embedding_model_metrics),
    path("api/settings/embedding-model/cache/clear", views.clear_embedding_model_cache),
    path(
        "api/settings/embedding-model/cache/clear/", views.clear_embedding_model_cache
    ),
    # Document Summarization endpoints
    path("api/summary/generate", views.generate_summary),
    path("api/summary/generate/", views.generate_summary),
    path("api/summary/history", views.get_summary_history),
    path("api/summary/history/", views.get_summary_history),
    path("api/summary/<str:summary_id>/delete", views.delete_summary),
    path("api/summary/<str:summary_id>/delete/", views.delete_summary),
    path("api/summary/regenerate", views.regenerate_summary),
    path("api/summary/regenerate/", views.regenerate_summary),
    # Question Suggestion endpoints
    path("api/suggestions", views.get_question_suggestions),
    path("api/suggestions/", views.get_question_suggestions),
    path("api/suggestions/click", views.record_suggestion_click),
    path("api/suggestions/click/", views.record_suggestion_click),
    path("api/suggestions/history", views.get_suggestion_history),
    path("api/suggestions/history/", views.get_suggestion_history),
    # SPA catch-all: serve Vue frontend for any non-API route
    re_path(r"^(?!api/).*$", views.index_page),
]

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
