from django.urls import path, re_path

from django_app import views

urlpatterns = [
    path("", views.index_page),
    path("api", views.root),
    path("api/", views.root),
    path("chat-demo", views.chat_demo_page),
    path("health", views.health_check),
    path("health/", views.health_check),
    path("api/upload", views.upload_pdf),
    path("api/upload/", views.upload_pdf),
    path("api/upload/status", views.upload_index_status),
    path("api/upload/status/", views.upload_index_status),
    path("api/files", views.list_files),
    path("api/files/", views.list_files),
    path("api/documents", views.list_documents),
    path("api/documents/", views.list_documents),
    path("api/documents/delete", views.delete_document),
    path("api/documents/delete/", views.delete_document),
    path("api/summarize", views.summarize_doc),
    path("api/summarize/", views.summarize_doc),
    path("api/podcast", views.generate_podcast),
    path("api/podcast/", views.generate_podcast),
    path("api/ask", views.ask_question),
    path("api/ask/", views.ask_question),
    path("api/chat", views.ask_qwen),
    path("api/chat/", views.ask_qwen),
    path("api/ask_qwen", views.ask_qwen),
    path("api/ask_qwen/", views.ask_qwen),
    path("api/settings", views.settings_handler),
    path("api/settings/", views.settings_handler),
    path("api/rag-config", views.get_rag_config),
    path("api/rag-config/", views.get_rag_config),
    path("api/rag-config/update", views.update_rag_config),
    path("api/rag-config/update/", views.update_rag_config),
    path("api/index/reset", views.reset_faiss_index),
    path("api/index/reset/", views.reset_faiss_index),
    path("chat-htmx", views.chat_htmx),
    path("chat-htmx/", views.chat_htmx),
    path("api/retrieve", views.retrieve_chunks),
    path("api/retrieve/", views.retrieve_chunks),
    # SPA catch-all: serve index.html for any route not matched above
    # so React Router can handle client-side paths like /config
    re_path(r"^(?!api/).*$", views.index_page),
]
